#cloud-config
runcmd:
  -  sudo mkfs.ext4 -L RANCHER_STATE /dev/sda
hostname : prod2w
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHhsg/RBS1eofdBtOmRgnk6rQeWL5eDCAFRYatomonqzVPHnUhGAWLwpAinTKY0breG7RwcPzSy8fE3lpAxd7d551SkowQOzLO1auRTvCGgGJMCYhsiOTDdg4yCGdhuvTlgG2Ox8cCEY93Nsh4bjX3m6l9bpqWamdlX5RH5bLypz5lq/Cd3eTprFXCgqJOcRT/7A2TqDeHKvE3zYM6tegke+dQadN41rh9sY3KCG0qfF58tn2FLzJx73H9wRGeCWxThrF5wSzgrFDIYGTJTMUqKgbJVVYWX/bY/nQWT8VO6fLzi+0pAOz931q4enHtO56T44bEqtfg5dSx7bLGIr56Hmln1GHhouU+u76cVTWOojDV5T1WsRATt8aD907Ci97FP/46cR5yJTxaTp+pxWpmh2waGeDRDWQstElHoSjtPyouyUuWb31oTBlk8KwgOep3z17q+YIhZWQGHvmcRKH2PA98IRpiJVRzf8sXJ0cdkouA5WBSDegToB5W7QPmehE= shadowchamber@Shadowchambers-Mac-mini.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/QU3JR6ZPpIqjeb+yT3ATTPElHfP4XgbhnhExThZN+XGo8UOx9NygGw98FXXVvDfOMl7hQBnsqkO1u1YzutBZTx+yejs/FyGFp6fK7x9I1Qhbwpkccn5R2QzvgtYQd+u6lBM//Wl/4pI0BxDUxDR9D8KXSyyeiww5hqYsAfEQpdlZ7IKUsdPW8SyF8XFXLJr/7qwOQqAn/DjWelfSa5T4Uyea+eK43CguDR0cH+H/39pmNme6WRpj9/+vgCHiJEmHeOsoZO6MBdesCncksev8g9/LvwBC2Dl0kVJ0ElXipQgMyTVN2jYMQXFbrJOEFx/K/UUM4B01CMPA66Y8NtFp andreypylypenko@Andreys-MacBook.local
rancher:
  network:
    interfaces:
      eth0:
        address: 10.11.1.13/24
        gateway: 10.11.1.254
        mtu: 1500
        dhcp: false
